import '../styles/globals.scss'
import type {Metadata} from 'next'
import {Archivo} from 'next/font/google'
import {Roboto} from 'next/font/google'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  style: ['normal'],
  variable: '--font-roboto',
})

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  style: ['normal'],
  variable: '--font-archivo',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} ${roboto.variable} ${archivo.variable}`}
      >
        {children}
      </body>
    </html>
  )
}
